// Generated by IcedCoffeeScript 1.3.3f
(function() {
  var friendsInvited, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  now.ready(function() {
    return FB.getLoginStatus(function(loginStatus) {
      var userid;
      if (!(loginStatus != null) || !(loginStatus.authResponse != null) || !(loginStatus.authResponse.accessToken != null)) {
        window.location = '/auth/facebook';
        return;
      }
      userid = loginStatus.authResponse.userID;
      console.log('nowjs initialized');
      FB.api('/me', function(response) {
        if (!(response != null) || !(response.name != null)) {
          window.location = '/auth/facebook';
        }
        return $('#username').text(response.name);
      });
      now.getStatus(userid, function(status) {
        return $('#status').text(status);
      });
      root.friendlist = [];
      return FB.api('/me/friends', function(response) {
        var friend, _i, _len, _ref, _results;
        if (!(response != null) || !(response.data != null)) {
          window.location = '/auth/facebook';
        }
        $('#friendinvitelist').html('');
        _ref = response.data;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          friend = _ref[_i];
          console.log(friend);
          root.friendlist.push(friend.name);
          _results.push($('#friendinvitelist').append($("<div>").addClass('friend-wrapper').append($('<input>').addClass('invitableFriend').attr('friendname', friend.name).attr('friendid', friend.id).attr('type', 'checkbox')).append("<span class='friend-info'>" + friend.name + " </span>")));
        }
        return _results;
      });
    });
  });

  friendsInvited = root.friendsInvited = function() {
    var allowedFriendIds, friend, friendid, friendname, _i, _len, _ref;
    allowedFriendIds = [];
    _ref = $('.invitableFriend');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      friend = _ref[_i];
      friendname = $(friend).attr('friendname');
      friendid = $(friend).attr('friendid');
      if ($(friend).is(':checked')) allowedFriendIds.push(friendid);
    }
    console.log('invited friends');
    return now.setFriendsAllowed(myid, allowedFriendIds);
  };

  now.refreshStatus = function(targetuser, newstatus) {
    if (root.email === targetuser) return $('#status').text(newstatus);
  };

}).call(this);
